version: "3.7"
services:
  envoy:
    image: envoyproxy/envoy-dev:latest
    ports:
    - "8000:8000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml

  ext_authz-opa-service:
    image: openpolicyagent/opa:0.39.0-envoy
    volumes:
    - ./policy:/etc
    command:
    - run
    - --server
    - --log-format=json-pretty
    - --set=plugins.envoy_ext_authz_grpc.addr=:9002
    - --set=plugins.envoy_ext_authz_grpc.enable-reflection=true
    - --set=decision_logs.console=true
    - --watch
    - /etc

  upstream-service:
    build: docker/
    volumes:
    - ./upstream/service.py:/code/service.py

  keycloak:
    # document for keycloak docker image
    # https://www.keycloak.org/server/containers
    image: quay.io/keycloak/keycloak
    ports:
    - "8080:8080"
    command:
    - start-dev
    - --features=preview
    - --features=upload-scripts
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_FRONTEND_URL: http://localhost:8080/auth
